### ISSUE TITLE
[DOCS] Add resource processor

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz.io#1108]
Add something like this so that azure events logs can be filtered

```
processors:
  resource/azure:
    attributes:
    - key: source_type
      value: "azureeventhub"
      action: upsert

service:
  pipelines:
    logs:
      receivers: [otlp, azureeventhub]
      processors: [batch]
      exporters: [otlp]
    logs/azure:
      receivers: [azureeventhub]
      processors: [resource/azure, batch]
      exporters: [otlp]
```

In this doc https://signoz.io/docs/azure-monitoring/bootstrapping/collector-setup/
