### ISSUE TITLE
Update in docs instructions on adding alerts for RPS for a service

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io#151]
Rules for checking for all services

```
        alert: Service Down
        expr: sum(rate(signoz_latency_count{span_kind="SPAN_KIND_SERVER"}[2m])) by (service_name) == 0
        for: 0m
        labels:
            severity: severe
        annotations:
            summary: Service is down
            description: RPS has gone down to 0
			 VALUE = {{ $value }}
			 LABELS = {{ $labels }}"
```

replace `expr` with 

sum(rate(signoz_latency_count{span_kind="SPAN_KIND_SERVER", service_name='xyz'}[2m])) == 0
for checking a specific service
