### ISSUE TITLE
Document signoz's sensitivity to `deployment.environment` resource attribute

### ISSUE THREAD

**Issue by EricThompson-PeopleReign** [SigNoz/signoz.io#74]
When trying to ship telemetry from more than one environment (e.g. Customer A deployment of app X and Customer B deployment of app X), one must set the `deployment.environment` resource attribute to allow signoz to "slice" that data in the Services page.  Without that resource attribute set the Services page will show _combined_ APM metrics.

Example sidecar collector:
```yaml
    processors:
      batch:
      resource/k8s:
        attributes:
          - key: deployment.environment
            value: dev
            action: upsert
```

This otel processor will add the `deployment.environment` resource attribute and set it to `dev` for all telemetry flowing through it.  Side cars from other customer environments could have different values, allowing the slicing in the Services page.

Maybe a new page with "hint and tips" for multi environment setups would be good?  It would have saved our team _alot_ of time.
